#pragma once

#define CUSTOM_OBJECT_DETECTOR_MAJOR_VERSION 1
#define CUSTOM_OBJECT_DETECTOR_MINOR_VERSION 0
#define CUSTOM_OBJECT_DETECTOR_PATCH_VERSION 0

#define CUSTOM_OBJECT_DETECTOR_VERSION "1.0.0"
